title: "ZL1ROD Rodney Amateur Radio Club"
description: "Welcome to our club website"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: "default"

navigation: true  # we see top bar

# Global default values applied to collections and pages during build
defaults:
  - scope:
      path: "" # An empty string means apply to ALL files in the repository
      type: "pages" # Applies specifically to static page files (.md, .html)
    values:
      layout: "single" # Forces pages to use the layout container that supports sidebars
      #classes: "wide" # Forces ALL markdown pages to use the expanded right margin layout
      # overriding toc instead to show widgets
      sidebar:
        nav: "site_sidebar" # Injects your custom sidebar menu configuration automatically
      toc: false # Tells the theme framework to construct the right column space on all pages

